
# Agent distribution (total should be your target network size)
agent_distribution:
  honest_user: 1
  group_creator: 1

# Agent profiles and their actions
profiles:
  honest_user:
    description: "Regular network participant with standard behavior"
    base_config:
      target_account_count: 1  # Number of accounts this agent controls
      max_daily_actions: 20    # Maximum actions per day
      risk_tolerance: 0.3      # Risk factor 0-1
      preferred_networks: ["gnosis"]  # Preferred networks
      
    available_actions:   
      - action: "ringshub_PersonalMint"
        probability: 0.8
        cooldown_blocks: 10
        constraints:
          max_executions: 100000
          
      - action: "ringshub_Trust"
        probability: 0.5
        cooldown_blocks: 1
        constraints:
          max_executions: 1

      - action: "ringshub_GroupMint"
        probability: 0.4
        cooldown_blocks: 1
        max_value: 50.0
        constraints:
          max_executions: 100

      - action: "ringshub_Burn"
        probability: 0.4
        cooldown_blocks: 1
        max_value: 50.0
        constraints:
          max_executions: 100

          

  group_creator:
    description: "Creates and manages groups"
    base_config:
      target_account_count: 1
      max_daily_actions: 30
      risk_tolerance: 0.5
      preferred_networks: ["gnosis"]
      
    available_actions:
      - action: "ringshub_RegisterGroup"
        probability: 1
        cooldown_blocks: 1
        constraints:
          max_executions: 1
        
      - action: "ringshub_Trust"
        probability: 0.5
        cooldown_blocks: 1
        constraints:
          max_executions: 1
 