# Base simulation parameters
simulation_params:
  initial_balance: 100  # Initial balance for new accounts
  welcome_bonus: 200    # Welcome bonus for registration
  min_gas_price: 0
  max_gas_price: 50000000000
  mint_policy_address: "0x79Cbc9C7077dF161b92a745345A6Ade3fC626A60"

# Agent distribution (total should be your target network size)
agent_distribution:
  honest_user: 10
  group_creator: 1
  sybil_attacker: 2
  trust_hub: 5

# Agent profiles and their actions
profiles:
  honest_user:
    description: "Regular network participant with standard behavior"
    base_config:
      target_account_count: 1  # Number of accounts this agent controls
      max_daily_actions: 20    # Maximum actions per day
      risk_tolerance: 0.3      # Risk factor 0-1
      preferred_networks: ["gnosis"]  # Preferred networks
      
    available_actions:
      - action: "ringshub_PersonalMint"
        probability: 0.8
        cooldown_blocks: 240
        constraints:
          max_executions: 100
          required_actions: ["ringshub_RegisterHuman"]
          min_balance: 0
          
      - action: "ringshub_SafeTransferFrom"
        probability: 0.3
        cooldown_blocks: 20
        max_value: 10.0
        constraints:
          require_trusted_target: true
          min_trust_age: 86400  # 1 day
          min_balance: 0.1
          
      - action: "ringshub_Trust"
        probability: 0.1
        cooldown_blocks: 100
        constraints:
          max_trusted_accounts: 50
          min_target_age: 86400  # 1 day
          trust_score_threshold: 0.6

  group_creator:
    description: "Creates and manages groups"
    base_config:
      target_account_count: 3
      max_daily_actions: 30
      risk_tolerance: 0.5
      preferred_networks: ["gnosis"]
      
    available_actions:
      - action: "ringshub_RegisterGroup"
        probability: 0.9
        cooldown_blocks: 1000
        constraints:
          max_groups: 5
          min_trust_connections: 10
          
      - action: "ringshub_PersonalMint"
        probability: 0.2
        cooldown_blocks: 240
        constraints:
          max_executions: 100
          
      - action: "ringshub_GroupMint"
        probability: 0.4
        cooldown_blocks: 100
        max_value: 50.0
        constraints:
          min_collateral_ratio: 1.5
          max_mint_per_day: 1000.0
          
      - action: "balancerv3vault_Swap"
        probability: 0.3
        cooldown_blocks: 50
        max_value: 20.0
        constraints:
          max_slippage: 0.02
          min_pool_liquidity: 1000.0

  sybil_attacker:
    description: "Creates multiple accounts for network manipulation"
    base_config:
      target_account_count: 50
      max_daily_actions: 100
      risk_tolerance: 0.8
      preferred_networks: ["gnosis"]
      
    available_actions:
      - action: "ringshub_RegisterHuman"
        probability: 1.0
        cooldown_blocks: 1
        constraints:
          max_accounts_per_day: 5
          
      - action: "ringshub_Trust"
        probability: 0.3
        cooldown_blocks: 1
        constraints:
          trust_targets: "controlled_accounts"
          circular_trust: true
          
      - action: "ringshub_SafeTransferFrom"
        probability: 0.3
        cooldown_blocks: 15
        max_value: 10.0
        constraints:
          preferred_targets: "trusted_accounts"

      - action: "ringshub_Wrap"
        probability: 0.8
        cooldown_blocks: 15
        max_value: 10.0
        constraints:
          min_balance: 1.0

  trust_hub:
    description: "Highly connected node that facilitates trust paths"
    base_config:
      target_account_count: 1
      max_daily_actions: 50
      risk_tolerance: 0.4
      preferred_networks: ["gnosis"]
      
    available_actions:
      - action: "ringshub_Trust"
        probability: 0.5
        cooldown_blocks: 10
        constraints:
          max_trust_connections: 200
          min_trustee_age: 604800  # 1 week
          trust_score_threshold: 0.6
          
      - action: "ringshub_SafeTransferFrom"
        probability: 0.3
        cooldown_blocks: 30
        max_value: 5.0
        constraints:
          preferred_targets: "trusted_accounts"
          