# Base network parameters (no nested 'network' key)
size: 20              # Default network size
trust_density: 0.1         # Default trust density
batch_size: 10           # Default processing batch size
iterations: 3              # Default number of iterations
blocks_per_iteration: 100  # Default blocks per iteration
block_time: 5            # Default seconds per block

# Gas configuration
gas_limits:
  register_human: 500000
  trust: 300000
  mint: 300000
  transfer: 300000
  create_group: 1000000

# Cache settings
cache:
  enabled: true
  ttl: 100

# Database configuration
db_path: "rings_simulation.duckdb"

# Trust parameters
trust:
  duration_days: 365
  min_connections: 3
  max_connections: 100