# Base simulation parameters
simulation_params:
  initial_balance: 100  # Initial balance for new accounts
  welcome_bonus: 200    # Welcome bonus for registration
  min_gas_price: 0
  max_gas_price: 50000000000
  mint_policy_address: "0x79Cbc9C7077dF161b92a745345A6Ade3fC626A60"

# Agent distribution (total should be your target network size)
agent_distribution:
  circles_user: 1

# Agent profiles and their actions
profiles:
  circles_user:
    description: "Regular network participant"
    base_config:
      target_account_count: 1
      max_executions: 10
      risk_tolerance: 0.5
      sequence_probability: 0.7
      max_sequence_iterations: 10
      preset_addresses: 
        - "0x42cEDde51198D1773590311E2A340DC06B24cB37"

    action_sequences:
      - name: "deposit_and_join_sequence"
        max_executions: 5
        steps:
          - action: "batchcall_BatchCall"
            repeat: 1
            batchcall:
              deposit_and_swap: 1
            constraints: {}
            params:
              value: "1000000000000000000"  # 1 xDAI

          - action: "balancerv2vault_JoinPool"
            repeat: 1
            constraints:
              token0_min: 0.001
              token0_max: 1.0

    available_actions:   
      - action: "circleshub_Trust"
        probability: 0.8
        cooldown_blocks: 2
        max_executions: 5

      - action: "batchcall_BatchCall"
        probability: 0
        cooldown_blocks: 0
        max_executions: 0
        batchcall: "deposit_and_swap"
