# Base network parameters (no nested 'network' key)
size: 20             # Default network size
trust_density: 0.5         # Default trust density
batch_size: 10           # Default processing batch size
iterations: 100              # Default number of iterations
blocks_per_iteration: 10  # Default blocks per iteration
block_time: 5            # Default seconds per block


state_variables:
  CirclesHub:  # Contract identifier matching contract_configs
    address: "0xc12C1E50ABB450d6205Ea2C3Fa861b3B834d13e8"  # Optional override
    variables:
      inflationDayZero:
        type: uint256
        slot: 0
      avatars:
        type: mapping(address => address)
        slot: 26
        iterable: true
      _uri:
        type: string
        slot: 20

        
strategies:
  circleshub: 'basic'  # or 'sybil'
  wxdai: 'basic'
  balancerv3vault: null


# Gas configuration
gas_limits:
  registerHuman: 500000
  trust: 300000
  registerGroup: 1000000

# Database configuration
db_path: "rings_simulation.duckdb"

# Trust parameters
trust:
  duration_days: 365
  min_connections: 3
  max_connections: 100000